name: Import WPL events on a CRON Schedule

on:
  schedule:
    # Runs every Wednesday at 7:50am
    - cron: '50 7 * * 3'
  push:
    branches:
      - 'wpl_integration'
jobs:
  build:
    name: Import WPL events
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the API endpoint to trigger an import
        run: |
          curl -s -X POST https://www.connectedkw.com/api/events/import \
            -d '{"source":"Waterloo Public Library"}' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.CONNECTEDKW_SECRET_KEY }}' \