name: Import the City of Waterloo events on a CRON Schedule

on:
  schedule:
    # Runs every Friday at 7:10am
    - cron: '10 7 * * 5'
  push:
    branches:
      - 'waterloo_integration'
jobs:
  build:
    name: Import City of Waterloo events
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the API endpoint to trigger an import
        run: |
          curl -s -X POST https://www.connectedkw.com/api/import-events \
            -d '{"source":"waterloo"}' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.UNBORING_SECRET_KEY }}' \