name: Import the RoW Museums events on a CRON Schedule

on:
  schedule:
    # Runs every Wednesday at 7:30am
    - cron: '30 7 * * 3'
  push:
    branches:
      - 'apify_integration_museums'
jobs:
  build:
    name: Import RoW museums events
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the API endpoint to trigger an import
        run: |
          curl -s -X POST https://www.connectedkw.com/api/events/import \
            -d '{"source":"museums"}' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.CONNECTEDKW_SECRET_KEY }}' \