name: Import the City of Cambridge events on a CRON Schedule

on:
  schedule:
    # Runs every Friday at 7:20am
    - cron: '20 7 * * 5'
  push:
    branches:
      - 'apify_integration_cambridge'
jobs:
  build:
    name: Import City of Cambridge events
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the API endpoint to trigger an import
        run: |
          curl -s -X POST https://www.connectedkw.com/api/import-events \
            -d '{"source":"cambridge"}' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.UNBORING_SECRET_KEY }}' \