name: Import Eventbrite events on a CRON Schedule

on:
  schedule:
    # Runs every Wednesday at 8:00am
    - cron: '0 8 * * 3'
  push:
    branches:
      - 'eventbrite_integration'
jobs:
  build:
    name: Import Eventbrite events
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the API endpoint to trigger an import
        run: |
          curl -s -X POST https://www.connectedkw.com/api/events/import \
            -d '{"source":"Eventbrite"}' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.CONNECTEDKW_SECRET_KEY }}' \